version: '3.2'

services:

  mongo_db:
    image: mongo
    container_name: mongo_nestjs
    restart: always
    ports:
      - '27717:27017'
      

  redis:
    image: redis
    container_name: nestjs_redis
    ports:
      - "6379:6379"
    volumes:
      - ~/docker-data/nestjs/redis:/usr/local/etc/redis